name: NovaGems
version: ${version}
main: net.watones.novagems.NovaGemsPlugin
api-version: '1.21'
authors: [Watones]
description: Economía secundaria por ciclos de sesión para Paper.
softdepend: [PlaceholderAPI]
libraries:
  - com.zaxxer:HikariCP:7.0.2
  - org.xerial:sqlite-jdbc:3.51.1.0
  - com.mysql:mysql-connector-j:9.6.0
commands:
  gemas:
    description: Abre el menú de canjes y consulta tu saldo de gemas.
    usage: /gemas
  novagems:
    description: Panel administrativo de NovaGems (solo staff con /op).
    usage: /novagems
permissions:
  novagems.shop: {default: true}
  novagems.balance: {default: true}
