name: NovaCoins
version: ${version}
main: net.watones.novacoins.NovaCoinsPlugin
api-version: '1.21'
authors: [Watones]
description: Economía secundaria por ciclos de sesión para Paper.
softdepend: [PlaceholderAPI]
libraries:
  - com.zaxxer:HikariCP:7.0.2
  - org.xerial:sqlite-jdbc:3.51.1.0
  - com.mysql:mysql-connector-j:9.6.0
commands:
  watacoins:
    description: Abre el menú de canjes de WataCoins.
    usage: /watacoins
permissions:
  novacoins.shop: {default: true}
  novacoins.balance: {default: true}
