package net.watones.novagems.shop;

public enum PurchaseResult {
  SUCCESS,
  BUSY,
  ACCOUNT_NOT_READY,
  ACCOUNT_MUTATION_PENDING,
  INSUFFICIENT_FUNDS,
  INVENTORY_FULL,
  INVALID_REWARD,
  DELIVERY_FAILED,
  PENDING_CONFIRMATION,
  MANUAL_REVIEW,
  DATABASE_UNAVAILABLE,
  JOURNAL_PROTECTED
}
